<?php
$title = 'Edit contact';
$this->headTitle($title);
?>
<h1><?php echo $this->escape($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', 
    $this->url('contact', array('action' => 'edit', 'id'=>$this->id)));

echo $this->form()->openTag($form);
?>
<dl class="zend_form">
<?php echo $this->formInput($form->get('id')); ?>
<dt><?php echo $this->formLabel($form->get('forename')); ?></dt>
<dd><?php 
    echo $this->formInput($form->get('forename'));
    echo $this->formElementErrors($form->get('forename'));
?></dd>
<dt><?php echo $this->formLabel($form->get('surname')); ?></dt>
<dd><?php 
    echo $this->formInput($form->get('surname'));
    echo $this->formElementErrors($form->get('surname'));
?></dd>

<dd><?php 
    echo $this->formInput($form->get('submit'));
    echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>
<?php echo $this->form()->closeTag($form); ?>
