<?php 
$title = 'My contacts';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('contact', array( 
        'action'=>'add'));?>">Add new contact</a></p>

<table class="table">
<tr>
    <th>Forename</th>
    <th>Surname</th>
    <th>Nickname</th>
    <th>Category</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($contacts as $contact) : ?>
<tr>
    <td><?php echo $this->escapeHtml($contact->forename);?></td>
    <td><?php echo $this->escapeHtml($contact->surname);?></td>
    <td><?php echo $this->escapeHtml($contact->nickname);?></td>
    <td><?php echo $this->escapeHtml($contact->category);?></td>
    <td>
        <a href="<?php echo $this->url('contact',
            array('action'=>'edit', 'id' => $contact->id));?>">Edit</a>
        <a href="<?php echo $this->url('contact',
            array('action'=>'delete', 'id' => $contact->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
